-- MySQL Script generated by MySQL Workbench
-- 12/02/14 22:43:58
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dcz4
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dcz4
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dcz4` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `dcz4` ;

-- -----------------------------------------------------
-- Table `dcz4`.`Friend`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dcz4`.`Friend` (
  `idFriend` INT NOT NULL AUTO_INCREMENT,
  `password` VARCHAR(45) NULL,
  `fName` VARCHAR(45) NULL,
  `surName` VARCHAR(45) NULL,
  `address1` VARCHAR(45) NULL,
  `address2` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `state` VARCHAR(2) NULL,
  `zipCode` INT NULL,
  `telephone` INT NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`idFriend`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dcz4`.`Payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dcz4`.`Payment` (
  `idPayment` INT NOT NULL AUTO_INCREMENT,
  `fk(Friend)_idPayer` INT NOT NULL,
  `category` VARCHAR(45) NULL,
  `dueAmount` DECIMAL(25) NULL,
  `paidAmount` DECIMAL(25) NULL,
  `deadline` DATE NULL,
  `paymentMethod` VARCHAR(45) NULL,
  PRIMARY KEY (`idPayment`, `fk(Friend)_idPayer`),
  INDEX `fk_Payment_Member_idx` (`fk(Friend)_idPayer` ASC),
  CONSTRAINT `fk(Friend)_idPayer`
    FOREIGN KEY (`fk(Friend)_idPayer`)
    REFERENCES `dcz4`.`Friend` (`idFriend`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dcz4`.`VolunteerHours`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dcz4`.`VolunteerHours` (
  `idVolunteerHours` INT NOT NULL AUTO_INCREMENT,
  `fk(Friend)_idVolunteer` INT NOT NULL,
  `organization` VARCHAR(45) NULL,
  `dateHours` DATE NULL,
  `eventName` VARCHAR(45) NULL,
  `eventType` VARCHAR(45) NULL,
  `hours` DECIMAL(5) NULL,
  `travelMileage` DECIMAL(5) NULL,
  PRIMARY KEY (`idVolunteerHours`, `fk(Friend)_idVolunteer`),
  INDEX `fk_VolunteerHours_Friend1_idx` (`fk(Friend)_idVolunteer` ASC),
  CONSTRAINT `fk(Friend)_idVolunteer`
    FOREIGN KEY (`fk(Friend)_idVolunteer`)
    REFERENCES `dcz4`.`Friend` (`idFriend`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dcz4`.`Member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dcz4`.`Member` (
  `fk(Friend)_idMember` INT NOT NULL,
  `committee` VARCHAR(45) NULL,
  `interest` VARCHAR(45) NULL,
  `category` VARCHAR(45) NULL,
  PRIMARY KEY (`fk(Friend)_idMember`),
  CONSTRAINT `fk(Friend)_idMember`
    FOREIGN KEY (`fk(Friend)_idMember`)
    REFERENCES `dcz4`.`Friend` (`idFriend`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dcz4`.`cardInfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dcz4`.`cardInfo` (
  `fk(Payment)_idPayment` INT NOT NULL AUTO_INCREMENT,
  `cardNumber` INT(16) NULL,
  `securityCode` INT(4) NULL,
  `expDate` DATE NULL,
  CONSTRAINT `fk(Payment)_idPayment`
    FOREIGN KEY (`fk(Payment)_idPayment`)
    REFERENCES `dcz4`.`Payment` (`idPayment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dcz4`.`Admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dcz4`.`Admin` (
  `fk(Friend)_idAdmin` INT NOT NULL AUTO_INCREMENT,
  `position` VARCHAR(45) NULL,
  PRIMARY KEY (`fk(Friend)_idAdmin`),
  CONSTRAINT `fk(Friend)_idAdmin`
    FOREIGN KEY (`fk(Friend)_idAdmin`)
    REFERENCES `dcz4`.`Friend` (`idFriend`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
